# put your secret values and credentials here. do not share this file and do not push it to github
[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.bigquery]
location = "EU"
#[destination.bigquery.credentials]
#project_id = "" # please set me up!
#private_key = "-----BEGIN PRIVATE KEY-----END PRIVATE KEY-----"
#client_email = "" # please set me up!
#

